### ISSUE TITLE
Impossible change toolbar?

### ISSUE THREAD

**Issue by hiroshi-nishiura** [pinzolo/redmine_persist_wfmt#12]
TextileからMarkdownへ移行するためにこのプラグイン導入させてもらいました。
ツールバーは切り替わらない仕様となっていますが、これ何とかなったりするでしょうか？

逆にこれ対応しちゃうとTextileの使い勝手が良くなてMarkdownへの移行が進まなくなるかもですが・・・

**Comment by pinzolo** [comment]
申し訳ありませんが、今のところ対応予定はありません。

**Comment by pinzolo** [comment]
Redmine4対応の最新版でサポートしました。そちらをお使いください。
