### ISSUE TITLE
Prevent conflicts with full text-search plugin

### ISSUE THREAD

**Issue by yassan** [pinzolo/redmine_persist_wfmt#13]
[clear-code/redmine_full_text_search: Full text search for Redmine](https://github.com/clear-code/redmine_full_text_search) と組み合わせて利用する場合、チケット作成時に500エラーが発生します。

先に、 redmine_full_text_search側にissueを挙げています （ clear-code/redmine_full_text_search#55 ) 。
そちらのissueにもコメントあるのですが、 同様の事例が、 two-pack/redmine_xlsx_format_issue_exporter#50 にもあったようです。

既存のtextileのチケットやwikiを維持したまま、Markdownを並行利用できるとても便利なプラグインなのでとても使いたいのですが、両方維持したまま、回避する方法はないでしょうか。

**Comment by pinzolo** [comment]
[clear\-code/redmine\_full\_text\_search: Full text search for Redmine](https://github.com/clear-code/redmine_full_text_search) の方で対応していただけたようなので（ありがとうございます）

こちらはクローズします
