### ISSUE TITLE
インストール時にエラー

### ISSUE THREAD

**Issue by TKinugasa** [pinzolo/redmine_persist_wfmt#9]
Windows版Bitnami Redmine Stack 2.6.2にインストールしていたら、
手順3のExecute migrationでエラーを出して停止してしまいました。

> rake aborted!
> NoMethodError: undefined method `before_render' for DocumentsController:Class
> C:/Bitnami/redmine-2.6.2-0/apps/redmine/htdocs/plugins/redmine_persist_wfmt/lib/patches/controller/documents_controller_patch.rb:5:in`block in module:DocumentsControllerPatch'
> C:/Bitnami/redmine-2.6.2-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/concern.rb:121:in `class_eval'
> …

**Comment by pinzolo** [comment]
`before_render` が存在しないということは `rails-render_hooks` がインストールされていないのではないでしょうか？
`bundle install` はされましたか？

**Comment by TKinugasa** [comment]
bundle installはその手前で実行して以下のように出力されていたので、rails-render_hooksは入っていると思いますが何か問題あるでしょうか?

> You are trying to install in deployment mode after changing
> your Gemfile. Run `bundle install` elsewhere and add the
> updated Gemfile.lock to version control.
>
> If this is a development machine, remove the Gemfile freeze
> by running `bundle install --no-deployment`.
> 
> You have added to the Gemfile:
> * rails-render_hooks
> * rspec (~> 2.14.0)
> * rspec-rails
> * coveralls
> * pry
> * pry-rails
> * pry-byebug
> * poltergeist
> * launchy
> * database_cleaner

**Comment by pinzolo** [comment]
確かに入っているようですね。
まずこちらで2.6.2でテストを流してみます。
